# Generated by Django 3.0 on 2019-12-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_auto_20191216_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civiljobs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itjobs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mechjobs',
            name='user',
        ),
    ]
