# Generated by Django 3.0 on 2019-12-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
        ('FirstApp', '0005_auto_20191216_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civiljobs',
            name='user',
        ),
        migrations.AddField(
            model_name='civiljobs',
            name='user',
            field=models.ManyToManyField(to='UserApp.User'),
        ),
        migrations.RemoveField(
            model_name='itjobs',
            name='user',
        ),
        migrations.AddField(
            model_name='itjobs',
            name='user',
            field=models.ManyToManyField(to='UserApp.User'),
        ),
        migrations.RemoveField(
            model_name='mechjobs',
            name='user',
        ),
        migrations.AddField(
            model_name='mechjobs',
            name='user',
            field=models.ManyToManyField(to='UserApp.User'),
        ),
    ]
