# Generated by Django 3.0 on 2019-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('conform_password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('resume', models.FileField(upload_to='files')),
            ],
        ),
    ]
