# Generated by Django 3.0 on 2019-12-17 13:14

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
